# -*- coding: utf-8 -*-
"""Issues.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5-55ZPFHna7EGD1IyMGx3Mde6RqSkBI

# Task
you are an ai engineer, read the issues.csv completely and write a model so that i can ask anything with respect to the data in issues.csv, dont use any pre trained llm

Here is all the data you need:
"issues.csv"

## Data loading

### Subtask:
Load the "issues.csv" file into a pandas DataFrame.
"""

import re
import nltk
from collections import defaultdict

nltk.download('punkt')
nltk.download('stopwords')

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)  # Remove punctuation
    tokens = nltk.word_tokenize(text)
    stop_words = set(nltk.corpus.stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]  # Remove stop words
    return tokens

def create_vocabulary(documents):
    vocabulary = set()
    for document in documents:
        tokens = preprocess_text(document)
        vocabulary.update(tokens)
    return list(vocabulary)

def create_bow_vector(document, vocabulary):
    bow_vector = defaultdict(int)
    tokens = preprocess_text(document)
    for token in tokens:
        if token in vocabulary:
            bow_vector[token] += 1
    return bow_vector

#Updated create_inverted_index
def create_inverted_index(all_issues_data):
    inverted_index = defaultdict(list)
    for column_name, column_data in all_issues_data.items():
        for i, value in enumerate(column_data):
            tokens = preprocess_text(str(value))  # Convert value to string
            for token in tokens:
                inverted_index[(column_name, token)].append(i)
    return inverted_index

def search_documents(query, inverted_index):
    query_tokens = preprocess_text(query)
    relevant_documents = set()
    column_name = None
    for column in all_issues_data.keys():
        if column.lower() in query.lower():
            column_name = column
            break

    if column_name is None:  # If column name not found in query
        print("No column name found")
        return []  # Return empty list indicating no relevant documents


    for token in query_tokens:
        if (column_name, token) in inverted_index:
            relevant_documents.update(inverted_index[(column_name, token)])
    return list(relevant_documents)

def extract_answer(all_issues_data, query, relevant_documents_indices):

    if relevant_documents_indices:
        # Get the column name from the query
        column_name = None
        for column in all_issues_data.keys():
            if column.lower() in query.lower():
                column_name = column
                break
        if column_name is None:
            return "No relevant documents found."

        # Extract data for the relevant indices from the specified column
        extracted_data = {}
        for i in relevant_documents_indices:
            row_data = {col: all_issues_data[col][i] for col in all_issues_data}
            extracted_data[i] = row_data  # Store each row's data using index as key

        # If only one row found, return it, otherwise return the dictionary of rows
        if len(extracted_data) == 1:
            return extracted_data[relevant_documents_indices[0]]
        else:
            return extracted_data

    else:
        return "No relevant documents found."

# Example usage with 'issues.csv' data
all_issues_data = {}
df_issues = pd.read_csv("issues.csv")

#issues_data = df_issues['Description'].tolist()
for column in df_issues.columns:
    all_issues_data[column] = df_issues[column].tolist()
vocabulary = create_vocabulary(issues_data)
inverted_index = create_inverted_index(all_issues_data)

query = "Give me details of Root_Cause where it was Malware"
relevant_documents_indices = search_documents(query, inverted_index)
answer = extract_answer(all_issues_data, query, relevant_documents_indices)

print(f"Question: {query}")
print(f"Answer: {answer}")